spring.application.name=MusicStore

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MelodyMartDB2;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE